#!/bin/bash

error() {
	echo $@ >&2
	exit 1
}

export SSHY_USER=
export SSHY_PASS=
export SSHY_HOST=
export SSHY_KEYFILE=

while getopts "l:i:p:" opt; do
	case $opt in
		l)
			SSHY_USER=$OPTARG
			;;
		i)
			SSHY_KEYFILE=$OPTARG
			;;
		p)
			SSHY_PASS=$OPTARG
			;;
	esac
done

shift $(($OPTIND - 1))
SSHY_HOST=$1
shift

if [ -z "$SSHY_USER" ] ; then SSHY_USER=$USER; fi

export SSHY_USER
export SSHY_PASS
export SSHY_HOST
export SSHY_KEYFILE

test -z "$SSHY_USER" && error "-l username required"
test -z "$SSHY_PASS" && test -z "$SSHY_KEYFILE" && error "-p password or -i keyfile required"
test -z "$SSHY_HOST" && error "hostname required"
test $# == 0 && error "command to tunnel required"

export LD_PRELOAD=./out/production/sshy/libsshy.so


$@

